### ISSUE TITLE
Voice Interaction throwing method errors in console

### ISSUE THREAD

**Issue by sheikah420** [iGalaxyYT/voicechat-interaction-paper#1]
Talking using voice chat throws this error every time in console:
[15:13:36] [Server thread/WARN]: [voicechat_interaction] Task #6444 for voicechat_interaction v1.0.0 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.World.sendGameEvent(org.bukkit.entity.Entity, org.bukkit.GameEvent, org.bukkit.util.Vector)'
        at dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.lambda$onMicPacket$0(VoiceChatInteractionPlugin.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1245) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:394) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1010) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
        at java.lang.Thread.run(Thread.java:833) [?:?]

This error is repeated every time a user talks, and voice chat is not activating sculk sensors.
I am on spigot CraftBukkit version 3551-Spigot-14a2382-9a8e080 (MC:1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
I have attached an image of the plugins I am using.
![image](https://user-images.githubusercontent.com/109487126/179428161-0348d1fe-bdfb-4d48-8fd7-28039f85b103.png)

**Comment by Kysha7** [comment]
I recommend you to use paper, pufferfish or purpur.

Those are .jar optimized, and I'm using this same plugin with purpur and no errors show up.

Paper is the base one, then pufferfish is a fork that optimized even more, and purpur is a fork of pufferfish and add some extra options that you may use or not.

https://github.com/YouHaveTrouble/minecraft-optimization this page allows you to optimized even more the server, you can see this page too https://purpurmc.org/docs/Configuration/
and this is from pufferfish team https://docs.pufferfish.host

Paper: https://papermc.io/downloads
Pufferfish: https://ci.pufferfish.host/job/Pufferfish-1.19/
Purpur: https://purpurmc.org

**Comment by sheikah420** [comment]
> I recommend you to use paper, pufferfish or purpur.

I installed purpur and now I am no longer getting that error and the sculker interactions now function correctly. Thank you for helping me correct this issue 👍
