### ISSUE TITLE
voice chat completely breaks when geyser floodgate Bedrock player uses Simple Voice Chat Discord Bridge, issue doesn't happen without voicechat interaction

### ISSUE THREAD

**Issue by ProGoofster** [iGalaxyYT/voicechat-interaction-paper#12]
voice chat completely breaks when geyser floodgate Bedrock player uses Simple Voice Chat Discord Bridge, issue doesn't happen without voicechat interaction. Logs below

[22:06:34] [epollEventLoopGroup-3-3/INFO]: [Geyser-Spigot] Player connected with username SoiledRook75642
[22:06:34] [defaultEventLoopGroup-6-3/INFO]: [Geyser-Spigot] SoiledRook75642 (logged in as: SoiledRook75642) has connected to the Java server
[22:06:35] [Geyser Spigot connection thread-5-4/INFO]: UUID of player SoiledRook75642 is 00000000-0000-0000-0009-01f3ae0218f3
[22:06:35] [Server thread/INFO]: [floodgate] Floodgate player logged in as SoiledRook75642 joined (UUID: 00000000-0000-0000-0009-01f3ae0218f3)
[22:06:35] [Server thread/INFO]: SoiledRook75642 joined the game
[22:06:35] [Server thread/INFO]: SoiledRook75642[/68.52.203.105:0] logged in with entity id 50057 at ([world]36.309036, 77.5, -180.42064)
[22:06:37] [Server thread/INFO]: ScholarlyNanobot issued server command: /msg SquaredDuck Ready. Just waiting for the audience to be seated
[22:06:52] [Server thread/INFO]: SquaredDuck issued server command: /tell SC64 sure, if everyone's okay with it
[22:06:57] [Server thread/INFO]: SoiledRook75642 issued server command: /dvc start
[22:06:57] [Thread-126/INFO]: [voicechat-discord] Started voice chat for SoiledRook75642 in channel Voice Link 1
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: java.lang.RuntimeException: Failed to decode audio data: Index 8 out of bounds for length 8
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-interaction-paper-v1.3.1+1.20.2.jar//dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.onMicPacket(VoiceChatInteractionPlugin.java:91)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:139)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.PluginManager.onMicPacket(PluginManager.java:242)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:302)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
[22:07:04] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: java.lang.RuntimeException: Failed to decode audio data: null
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: 	at voicechat-interaction-paper-v1.3.1+1.20.2.jar//dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.onMicPacket(VoiceChatInteractionPlugin.java:91)
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:139)
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.PluginManager.onMicPacket(PluginManager.java:242)
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:302)
[22:07:11] [VoiceChatPacketProcessingThread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: java.lang.RuntimeException: Failed to decode audio data: null
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:51)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-interaction-paper-v1.3.1+1.20.2.jar//dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.onMicPacket(VoiceChatInteractionPlugin.java:91)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:139)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.PluginManager.onMicPacket(PluginManager.java:242)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:302)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.sendMicrophonePacket(AudioSenderImpl.java:90)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-bukkit-2.4.30.jar//de.maxhenkel.voicechat.plugins.impl.audiosender.AudioSenderImpl.send(AudioSenderImpl.java:66)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.audiotransfer.DiscordBot.handleEncodedAudio(DiscordBot.java:383)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at voicechat-discord-paper-2.1.1.jar//dev.naturecodevoid.voicechatdiscord.shadow.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$4(AudioConnection.java:411)
[22:07:11] [JDA AudioConnection Guild: 1052771339024466001 Receiving Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:07:19] [VoiceChatPacketProcessingThread/ERROR]: [voicechat] Uncaught exception in thread VoiceChatPacketProcessingThread
java.lang.AssertionError: null
	at de.maxhenkel.voicechat.concentus.Inlines.OpusAssert(Inlines.java:40) ~[voicechat-bukkit-2.4.30.jar:?]
	at de.maxhenkel.voicechat.concentus.OpusDecoder.opus_decode_native(OpusDecoder.java:640) ~[voicechat-bukkit-2.4.30.jar:?]
	at de.maxhenkel.voicechat.concentus.OpusDecoder.decode(OpusDecoder.java:692) ~[voicechat-bukkit-2.4.30.jar:?]
	at de.maxhenkel.voicechat.plugins.impl.opus.JavaOpusDecoderImpl.decode(JavaOpusDecoderImpl.java:48) ~[voicechat-bukkit-2.4.30.jar:?]
	at dev.igalaxy.voicechatinteraction.VoiceChatInteractionPlugin.onMicPacket(VoiceChatInteractionPlugin.java:91) ~[voicechat-interaction-paper-v1.3.1+1.20.2.jar:?]
	at de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:139) ~[voicechat-bukkit-2.4.30.jar:?]
	at de.maxhenkel.voicechat.plugins.PluginManager.onMicPacket(PluginManager.java:242) ~[voicechat-bukkit-2.4.30.jar:?]
	at de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:302) ~[voicechat-bukkit-2.4.30.jar:?]
	at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269) ~[voicechat-bukkit-2.4.30.jar:?]
[22:07:25] [Server thread/INFO]: SquaredDuck issued server command: /tell SC64 actually no recording
[22:07:32] [Server thread/INFO]: SquaredDuck issued server command: /tell SC64 ive changed my mind, sorry
[22:07:43] [Async Chat Thread - #45/INFO]: <SC64> voice chat just broke just now!??
[22:07:45] [Async Chat Thread - #45/INFO]: <SC64> whyyyyy
[22:07:48] [Async Chat Thread - #46/INFO]: <BlueOddity28> love how it just broke
[22:07:51] [Async Chat Thread - #46/INFO]: <ScholarlyNanobot> Timing is impeccable

**Comment by ProGoofster** [comment]
I should also add this only appears to be a problem when a lot of people are on, I don't know quite what caused it
